server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: 127.0.0.1:8848
        server-addr: 192.168.183.128:1111 #找服务器的nginx使用负载均衡进nacos
management:
  endpoints:
    web:
      exposure:
        include: '*'

