server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        #server-addr: 127.0.0.1:8848
        server-addr: 192.168.183.128:1111 #找服务器的nginx使用负载均衡进nacos
#消费者将要去访问的微服务名称（成功注册进nacos的微服务提供者），在这配置了访问的服务，业务类就不用在定义常量了
service-url:
  nacos-user-service: http://nacos-payment-provider

